### ISSUE TITLE
Pretrained embeddings.

### ISSUE THREAD

**Issue by alvations** [ninjin/huang_et_al_2012#1]
@ninjin Do you happen to have the pre-trained embeddings from Huang's paper?

I know there's a copy of Luong's modified version here: https://nlp.stanford.edu/~lmthang/morphoNLM/ but I can't seem to find Huang's original embeddings =(

Thanks in advance, Pontus!

**Comment by ninjin** [comment]
@alvations Sadly, no, as far as I know they were never released.
